# Generated by Django 3.1.2 on 2020-11-20 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PostData', '0003_auto_20201120_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 20, 3, 19, 8, 252298, tzinfo=utc)),
        ),
    ]
