# Generated by Django 3.1.2 on 2020-11-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostData', '0005_auto_20201120_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
