# Generated by Django 3.1.2 on 2020-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostData', '0006_auto_20201120_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.ManyToManyField(blank=True, to='PostData.Tag'),
        ),
    ]
